name: momo_go
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  go_router: ^6.0.4
  animations: ^2.0.2
  mobile_scanner: ^3.2.0
  url_launcher: ^6.1.2
  shared_preferences: ^2.0.15
  intl: any
  google_fonts: ^4.0.1
  flutter_riverpod: any
  get: any
  flutter_svg: any




dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/
    - assets/google-fonts/
    - assets/svg/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/google-fonts/Roboto/Roboto-Black.ttf
        - asset: assets/google-fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/google-fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/google-fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/google-fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/google-fonts/Roboto/Roboto-Light.ttf
    - family: MTNBrighterSans
      fonts:
        - asset: assets/google-fonts/MTNBrighterSans_Latin/MTNBrighterSans-Bold.ttf
        - asset: assets/google-fonts/MTNBrighterSans_Latin/MTNBrighterSans-BoldItalic.ttf
        - asset: assets/google-fonts/MTNBrighterSans_Latin/MTNBrighterSans-ExtraBoldItalic.ttf
        - asset: assets/google-fonts/MTNBrighterSans_Latin/MTNBrighterSans-ExtraLight.ttf
        - asset: assets/google-fonts/MTNBrighterSans_Latin/MTNBrighterSans-ExtraLightItalic.ttf
        - asset: assets/google-fonts/MTNBrighterSans_Latin/MTNBrighterSans-Light.ttf
        - asset: assets/google-fonts/MTNBrighterSans_Latin/MTNBrighterSans-LightItalic.ttf
        - asset: assets/google-fonts/MTNBrighterSans_Latin/MTNBrighterSans-Medium.ttf
        - asset: assets/google-fonts/MTNBrighterSans_Latin/MTNBrighterSans-MediumItalic.ttf
        - asset: assets/google-fonts/MTNBrighterSans_Latin/MTNBrighterSans-Regular.ttf
        - asset: assets/google-fonts/MTNBrighterSans_Latin/MTNBrighterSans-RegularItalic.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
